### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [mashakiselyova/Telegram-screen#1]
Hello @mashakiselyova ,
The goal is to check and improve skill of creating markup based on design or mockup.
Current UI looking more or less good, but let's try to make it better! 
 - the UI looks broken under my laptop
![image](https://user-images.githubusercontent.com/5592397/87879208-01f01000-c9f2-11ea-8e85-39b868290203.png)
 - 
![image](https://user-images.githubusercontent.com/5592397/87879238-3663cc00-c9f2-11ea-85a6-b720deab935d.png)

 - also please add smiles, a few types of messages: link share, quoted text, audio, video in telegram style 

Thank you for the efforts!

**Comment by ilya4321** [comment]
Thanks, looks fine now. I am closing the ticket. Thanks for the efforts 
We will be checking your JS tasks soon

**Comment by mashakiselyova** [comment]
Thank you very much)
